### ISSUE TITLE
Reporting functionality question

### ISSUE THREAD

**Issue by 7MinSec** [LuccaSA/PingCastle-Notify#4]
Hello,

This looks REALLY cool.  Is there any - or do you have any plans to - export to any other reporting format?  It would be awesome even to get a txt or json dump just so I could quickly scan it and tell a customer what has changed between scan 1 and 2.

Thanks for all your awesome work/tools!

Brian

**Comment by mpgn** [comment]
Yes, this can be easily done, I will push an update tonight !

**Comment by 7MinSec** [comment]
What?  I told some of my friends you're a cyborg.  Your last message confirms it.  When do you sleep? :-)

**Comment by mpgn** [comment]
aha because i'm not a cyborg I will push tomorrow héhéhé

**Comment by mpgn** [comment]
check the branch https://github.com/LuccaSA/PingCastle-Notify/tree/teams and let me know 🦜

**Comment by 7MinSec** [comment]
Hey, this looks awesome!  I did scan 1 in my lab, then fixed the GPO issue, and scan 2 displays the update really nicely.  LOVE IT!

![pingcastlenotify](https://user-images.githubusercontent.com/17596787/193885810-8a06c9e1-8503-4fd0-a403-5d336ac194a8.png)

Thanks!

A follow-up question that's really unrelated to your tool - is it possible to have PowerShell display/convert the findings output with "pretty" emoji output?  I'm reading [this](https://www.powershellcenter.com/2021/02/19/add-emojis-to-powershell-output/#The_easy_way_-_PS7_and_Windows_Terminal_to_show_Powershell_emojis) and wondering if I'm making it too hard?

**Comment by mpgn** [comment]
you mean in the scan.log file or when you run the script ?

**Comment by 7MinSec** [comment]
I think seeing it "pretty" right in the Powershell output as the tool runs would be awesome for live demo and training purposes.  If it can be pretty in the log file too you won't hear any complaints from me.

**Comment by mpgn** [comment]
Pretty in the output in the console + log file => easy 

but for the emoji i'm not so sure as you need powershell from "terminal" aka 7.1 to be able to see them

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/194063423-6acce525-feec-4619-b1ef-1c897c8a888b.png)

**Comment by 7MinSec** [comment]
Ahhhh it's beauuuutiful! 

![image](https://user-images.githubusercontent.com/17596787/194075401-9ffe9796-3c40-480a-a4e3-348c1862902e.png)

Thank you!  Ok and I know I'm turning into a dirty rotten beggar at this point (and I could open a separate wish list request for this) but it would be awesome to have the option of sorting the output items by point value.  That way, for example, an org could look at the list and go "Darn, lets get some of these 20-point dings off the list first!"

**Comment by 7MinSec** [comment]
Thanks, yes that makes sense.  Much appreciated!!!
