### ISSUE TITLE
Feature Request - Offline diff 

### ISSUE THREAD

**Issue by yellow-starburst** [LuccaSA/PingCastle-Notify#7]
I have 2 pingcastle reports. 
Report A = New
Report B = 1 month old 

I would like to run an offline diff of the 2 reports and report the findings to a microsoft teams instance. 
Does PingCastle-Notify support that?

**Comment by mpgn** [comment]
Hello, follow this structure:
```
SECU-TOOL-SCAN/
    - PingCastle-Notify.ps1
    - PingCastle/
        - Reports/
            - domain.local.xml <------- your old report
        - ad_hc_domain.xml <-------- your new report
```
And the run the script PingCastle-Notify.ps1 :)
